vscode:
  extensions:
    - formulahendry.auto-complete-tag@0.1.0:XS3fJJUSAJ7NZnVWJBvrJQ==
    - techer.open-in-browser@2.0.0:Qv25RdB8dvt/hv1HZBwW/g==
    - 2gua.rainbow-brackets@0.0.6:Tbu8dTz0i+/bgcKQTQ5b8g==
    - thekalinga.bootstrap4-vscode@6.1.0:duaQhthWtxWBzXAGe+5GKQ==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==